from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path
from typing import Iterable

import lif_memory as core
import llm_adapter


VERSION = "0.1.0"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Review full LIF insights and Obsidian graph summaries with an LLM.")
    parser.add_argument("--vault", type=Path, default=None, help="Obsidian vault path.")
    parser.add_argument("--insights-json", type=Path, default=Path("lif_insights_full.json"), help="Full insight JSON generated by insight_integrator.py.")
    parser.add_argument("--graph-json", type=Path, default=Path("obsidian_lif_graph.json"), help="Graph JSON generated by obsidian_graph_miner.py.")
    parser.add_argument("--output", type=Path, default=Path("LIF-Memory DeepSeek 全量整合审查.md"), help="Markdown output path.")
    parser.add_argument("--top-insights", type=int, default=12, help="Number of top insight spikes sent to LLM.")
    parser.add_argument("--top-graph-notes", type=int, default=16, help="Number of top graph notes sent to LLM.")
    parser.add_argument("--dry-run", action="store_true", help="Print report instead of writing output.")
    llm_adapter.add_cli_args(parser)
    parser.add_argument("--version", action="version", version=f"LIF Report Reviewer {VERSION}")
    return parser.parse_args()


def resolve(vault: Path, path: Path) -> Path:
    return path if path.is_absolute() else vault / path


def load_json(path: Path) -> object:
    return json.loads(path.read_text(encoding="utf-8"))


def insight_rank(item: dict[str, object]) -> tuple[float, str]:
    voltage = float(item.get("V", 0.0))
    threshold = float(item.get("threshold", 1.0) or 1.0)
    fragments = item.get("integrated_fragments", [])
    fragment_bonus = min(len(fragments), 12) * 0.03 if isinstance(fragments, list) else 0.0
    return (voltage / threshold + fragment_bonus, str(item.get("time", "")))


def select_top_insights(insights: object, topn: int) -> list[dict[str, object]]:
    if not isinstance(insights, list):
        return []
    ranked = sorted(
        [item for item in insights if isinstance(item, dict)],
        key=insight_rank,
        reverse=True,
    )
    selected: list[dict[str, object]] = []
    for item in ranked[: max(0, topn)]:
        fragments = item.get("integrated_fragments", [])
        if not isinstance(fragments, list):
            fragments = []
        selected.append(
            {
                "latent_question": item.get("latent_question"),
                "time": item.get("time"),
                "V": item.get("V"),
                "threshold": item.get("threshold"),
                "emergent_insight": item.get("emergent_insight"),
                "next_validation_action": item.get("next_validation_action"),
                "top_fragments": fragments[:4],
            }
        )
    return selected


def graph_note_score(node: dict[str, object]) -> float:
    links = node.get("links", [])
    state_scores = node.get("state_scores", {})
    link_count = len(links) if isinstance(links, list) else 0
    score_total = sum(float(value) for value in state_scores.values()) if isinstance(state_scores, dict) else 0.0
    return float(node.get("inbound_count", 0)) * 1.5 + link_count + score_total * 0.35


def select_top_graph_notes(graph: object, topn: int) -> dict[str, object]:
    if not isinstance(graph, dict):
        return {"note_count": 0, "top_notes": []}
    nodes = graph.get("nodes", [])
    if not isinstance(nodes, list):
        nodes = []
    ranked = sorted(
        [node for node in nodes if isinstance(node, dict)],
        key=graph_note_score,
        reverse=True,
    )
    top_notes = []
    for node in ranked[: max(0, topn)]:
        top_notes.append(
            {
                "path": node.get("path"),
                "title": node.get("title"),
                "folder": node.get("folder"),
                "is_daily": node.get("is_daily"),
                "inbound_count": node.get("inbound_count"),
                "outbound_count": len(node.get("links", [])) if isinstance(node.get("links"), list) else 0,
                "state_scores": node.get("state_scores", {}),
                "tags": node.get("tags", []),
            }
        )
    return {
        "note_count": graph.get("note_count", len(nodes)),
        "top_notes": top_notes,
    }


def review_prompt(insight_payload: list[dict[str, object]], graph_payload: dict[str, object]) -> list[dict[str, str]]:
    system = (
        "你是 LIF-Memory 的全量整合审查器。"
        "你要基于已经压缩过的 insight spikes 和 Obsidian graph top notes 做二次综合。"
        "不要要求读取全文，不要改写 LIF 电压或策略。"
        "输出必须是 JSON object。"
    )
    user = {
        "task": "Synthesize the user's long-term Obsidian/LIF memory into top insights and next integration actions.",
        "required_output_schema": {
            "global_summary": "string",
            "top_insights": [
                {
                    "title": "string",
                    "why_it_matters": "string",
                    "evidence": ["string"],
                    "next_action": "string",
                }
            ],
            "main_blockers": [
                {
                    "blocker": "string",
                    "affected_topics": ["string"],
                    "recommended_policy": "continue|isolate|downgrade|recover_first",
                }
            ],
            "graph_observations": ["string"],
            "suggested_memory_system_upgrade": "string",
        },
        "insight_spikes": insight_payload,
        "graph_summary": graph_payload,
    }
    return [
        {"role": "system", "content": system},
        {"role": "user", "content": json.dumps(user, ensure_ascii=False, indent=2)},
    ]


def call_llm(insight_payload: list[dict[str, object]], graph_payload: dict[str, object], args: argparse.Namespace) -> dict[str, object]:
    config = llm_adapter.config_from_args(args)
    content = llm_adapter.call_chat_completions(config, review_prompt(insight_payload, graph_payload))
    return llm_adapter.extract_json_object(content)


def list_lines(items: Iterable[object]) -> list[str]:
    return [f"- {item}" for item in items if str(item).strip()]


def render_report(
    insights_path: Path,
    graph_path: Path,
    insight_payload: list[dict[str, object]],
    graph_payload: dict[str, object],
    review: dict[str, object],
) -> str:
    lines: list[str] = []
    lines.append("# LIF-Memory DeepSeek 全量整合审查")
    lines.append("")
    lines.append(f"生成时间：{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"版本：{VERSION}")
    lines.append(f"Insight JSON：{insights_path}")
    lines.append(f"Graph JSON：{graph_path}")
    lines.append(f"发送 top insights：{len(insight_payload)}")
    lines.append(f"发送 top graph notes：{len(graph_payload.get('top_notes', []))}")
    lines.append("")
    lines.append("## 全局总结")
    lines.append("")
    lines.append(str(review.get("global_summary", "")))
    lines.append("")
    lines.append("## Top Insights")
    lines.append("")
    top_insights = review.get("top_insights", [])
    if isinstance(top_insights, list):
        for index, item in enumerate(top_insights, start=1):
            if not isinstance(item, dict):
                continue
            lines.append(f"### {index}. {item.get('title', '')}")
            lines.append("")
            lines.append(f"- 为什么重要：{item.get('why_it_matters', '')}")
            evidence = item.get("evidence", [])
            if isinstance(evidence, list) and evidence:
                lines.append("- 证据：")
                for line in list_lines(evidence):
                    lines.append(f"  {line}")
            lines.append(f"- 下一步：{item.get('next_action', '')}")
            lines.append("")
    lines.append("## Main Blockers")
    lines.append("")
    blockers = review.get("main_blockers", [])
    if isinstance(blockers, list):
        for item in blockers:
            if not isinstance(item, dict):
                continue
            lines.append(f"- {item.get('blocker', '')}")
            lines.append(f"  - affected_topics：{item.get('affected_topics', [])}")
            lines.append(f"  - recommended_policy：{item.get('recommended_policy', '')}")
    lines.append("")
    lines.append("## Graph Observations")
    lines.append("")
    observations = review.get("graph_observations", [])
    if isinstance(observations, list):
        lines.extend(list_lines(observations))
    lines.append("")
    lines.append("## Suggested Memory System Upgrade")
    lines.append("")
    lines.append(str(review.get("suggested_memory_system_upgrade", "")))
    lines.append("")
    lines.append("## Sent Payload Index")
    lines.append("")
    lines.append("### Insight Spikes")
    lines.append("")
    for item in insight_payload:
        lines.append(f"- {item.get('time')} / {item.get('latent_question')} / V={item.get('V')}")
    lines.append("")
    lines.append("### Graph Notes")
    lines.append("")
    for item in graph_payload.get("top_notes", []):
        if isinstance(item, dict):
            lines.append(f"- {item.get('path')} / inbound={item.get('inbound_count')} / states={item.get('state_scores')}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    args = parse_args()
    vault = (args.vault or core.vault_root_from_script()).resolve()
    insights_path = resolve(vault, args.insights_json)
    graph_path = resolve(vault, args.graph_json)
    output = resolve(vault, args.output)

    insight_payload = select_top_insights(load_json(insights_path), args.top_insights)
    graph_payload = select_top_graph_notes(load_json(graph_path), args.top_graph_notes)
    review = call_llm(insight_payload, graph_payload, args)
    report = render_report(insights_path, graph_path, insight_payload, graph_payload, review)

    if args.dry_run:
        print(report)
    else:
        output.write_text(report, encoding="utf-8")
        print(f"Reviewed {len(insight_payload)} insights and {len(graph_payload.get('top_notes', []))} graph notes.")
        print(f"Wrote: {output}")


if __name__ == "__main__":
    main()
